#  Deep MNIST for Experts 

from: https://www.tensorflow.org/get_started/mnist/pros

"TensorFlow is a powerful library for doing large-scale numerical computation. One of the tasks at which it excels is implementing and training deep neural networks. In this tutorial we will learn the basic building blocks of a TensorFlow model while constructing a deep convolutional MNIST classifier.

This introduction assumes familiarity with neural networks and the MNIST dataset. If you don't have a background with them, check out the introduction for beginners. Be sure to install TensorFlow before starting."

## About this tutorial



The first part of this tutorial explains what is happening in the mnist_softmax.py code, which is a basic implementation of a Tensorflow model. The second part shows some ways to improve the accuracy.

You can copy and paste each code snippet from this tutorial into a Python environment to follow along, or you can download the fully implemented deep net from mnist_deep.py .

What we will accomplish in this tutorial:
<ul>
<li>Create a softmax regression function that is a model for recognizing MNIST digits, based on looking at every pixel in the image</li>
<li>Use Tensorflow to train the model to recognize digits by having it "look" at thousands of examples (and run our first Tensorflow session to do so)</li>
<li>Check the model's accuracy with our test data</li>
<li>Build, train, and test a multilayer convolutional neural network to improve the results</li>
</ul>
    


## Setup

### Load MNIST Data

"If you are copying and pasting in the code from this tutorial, start here with these two lines of code which will download and read in the data automatically:"

In [2]:
import tensorflow as tf

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)


Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [1]:
# https://es.stackoverflow.com/questions/15770/se-puede-incluir-c%C3%B3digo-css-en-jupyter

<!--
<style>
pre {
    display: block;
    font-family: monospace;
    white-space: pre;
    margin: 0em 0;
} 


<pre><span class="inner-pre" style="font-size: 11px">
Blah blah
Multiple lines and no br's!
Oh yeah!
</span></pre>


</style> -->

"Here<font face="monospace" size="5"> mnist </font>is a lightweight class which stores the training, validation, and testing sets as NumPy arrays. It also provides a function for iterating through data minibatches, which we will use below."



### Start TensorFlow InteractiveSession

"TensorFlow relies on a highly efficient C++ backend to do its computation. The connection to this backend is called a session. The common usage for TensorFlow programs is to first create a graph and then launch it in a session.

Here we instead use the convenient InteractiveSession class, which makes TensorFlow more flexible about how you structure your code. It allows you to interleave operations which build a computation graph with ones that run the graph. This is particularly convenient when working in interactive contexts like IPython. <u>If you are not using an InteractiveSession, then you should build the entire computation graph before starting a session and launching the graph.</u>"

In [3]:
import tensorflow as tf
sess = tf.InteractiveSession()

sess.close()

### Computation Graph

"To do efficient numerical computing in Python, we typically use libraries like NumPy that do expensive operations such as matrix multiplication outside Python, using highly efficient code implemented in another language. Unfortunately, there can still be a lot of overhead from switching back to Python every operation. This overhead is especially bad if you want to run computations on GPUs or in a distributed manner, where there can be a high cost to transferring data.

TensorFlow also does its heavy lifting outside Python, but it takes things a step further to avoid this overhead. Instead of running a single expensive operation independently from Python, TensorFlow lets us describe a graph of interacting operations that run entirely outside Python. This approach is similar to that used in Theano or Torch.

The role of the Python code is therefore to build this external computation graph, and to dictate which parts of the computation graph should be run. See the Computation Graph section of Getting Started With TensorFlow for more detail."

## Build a Softmax Regression Model

"In this section we will build a softmax regression model with a single linear layer. In the next section, we will extend this to the case of softmax regression with a multilayer convolutional network."

## Placeholders

"We start building the computation graph by creating nodes for the input images and target output classes."

In [4]:
import tensorflow as tf
sess = tf.InteractiveSession()

x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

"Here x and y_ aren't specific values. Rather, they are each a placeholder -- a value that we'll input when we ask TensorFlow to run a computation."

"The input images x will consist of a 2d tensor of floating point numbers. Here we assign it a shape of [None, 784], where 784 is the dimensionality of a single flattened 28 by 28 pixel MNIST image, and None indicates that the first dimension, corresponding to the batch size, can be of any size. The target output classes y_ will also consist of a 2d tensor, where each row is a one-hot 10-dimensional vector indicating which digit class (zero through nine) the corresponding MNIST image belongs to."

<font face="monospace" size="5"> mnist </font>

"The <font face="monospace" size="5">shape</font> argument to <font face="monospace" size="5">placeholder</font> is optional, but it allows TensorFlow to automatically catch bugs stemming from inconsistent tensor shapes."

## Variables

"We now define the weights W and biases b for our model. We could imagine treating these like additional inputs, but TensorFlow has an even better way to handle them: Variable. A Variable is a value that lives in TensorFlow's computation graph. It can be used and even modified by the computation. In machine learning applications, one generally has the model parameters be Variables."

In [5]:
W = tf.Variable(tf.zeros([784,10]))
b = tf.Variable(tf.zeros([10]))


"We pass the initial value for each parameter in the call to tf.Variable. In this case, we initialize both W and b as tensors full of zeros. W is a 784x10 matrix (because we have 784 input features and 10 outputs) and b is a 10-dimensional vector (because we have 10 classes)."

"Before Variables can be used within a session, they must be initialized using that session. This step takes the initial values (in this case tensors full of zeros) that have already been specified, and assigns them to each Variable. This can be done for all Variables at once:"

In [6]:
sess.run(tf.global_variables_initializer())


In [7]:
sess.close()

In [1]:
import tensorflow as tf

#sess = tf.InteractiveSession()

sess = tf.Session()

x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

W = tf.Variable(tf.zeros([784,10]), name='one')
b = tf.Variable(tf.zeros([10]), name='two')

#print(sess.run(tf.report_uninitialized_variables())) 

#sess.run(tf.global_variables_initializer())
#print(sess.run(tf.report_uninitialized_variables())) 
#from https://www.tensorflow.org/programmers_guide/variables#initializing_variables

#print(tf.report_uninitialized_variables())

#sess.close()

In [2]:
tf.variables_initializer(
    [v for v in tf.global_variables() if v.name.split(':')[0] in set(sess.run(tf.report_uninitialized_variables()))
])

<tf.Operation 'init' type=NoOp>

from https://stackoverflow.com/a/43601894 insteresting function to initialize initialize_uninitialized

In [5]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [1]:
import tensorflow as tf

sess = tf.InteractiveSession()

x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

W = tf.Variable(tf.zeros([784,10]), name='one')
b = tf.Variable(tf.zeros([10]), name='two')


print(W.eval)

tf.global_variables_initializer()

print(W.eval)

sess.close()

<bound method Variable.eval of <tf.Variable 'one:0' shape=(784, 10) dtype=float32_ref>>
<bound method Variable.eval of <tf.Variable 'one:0' shape=(784, 10) dtype=float32_ref>>


A little of more insight of why initialize variables, 
from: http://machinelearninguru.com/deep_learning/tensorflow/basics/variables/variables.html

<img src="imgs/init_variables.jpeg">

## Predicted Class and Loss Function

"We can now implement our regression model. It only takes one line! We multiply the vectorized input images x by the weight matrix W, add the bias b."

In [2]:
#all code till here
import tensorflow as tf

sess = tf.InteractiveSession()

x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

W = tf.Variable(tf.zeros([784,10]), name='one')
b = tf.Variable(tf.zeros([10]), name='two')

tf.global_variables_initializer()

y = tf.matmul(x,W) + b

In [4]:
type(y)

tensorflow.python.framework.ops.Tensor

In [3]:
y._op

<tf.Operation 'add' type=Add>

"We can specify a loss function just as easily. Loss indicates how bad the model's prediction was on a single example; we try to minimize that while training across all the examples. Here, our loss function is the cross-entropy between the target and the softmax activation function applied to the model's prediction. As in the beginners tutorial, we use the stable formulation:"

In [5]:
cross_entropy = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y))


"Note that tf.nn.softmax_cross_entropy_with_logits internally applies the softmax on the model's unnormalized model prediction and sums across all classes, and tf.reduce_mean takes the average over these sums."

## Train the Model

"Now that we have defined our model and training loss function, it is straightforward to train using TensorFlow. Because TensorFlow knows the entire computation graph, it can use automatic differentiation to find the gradients of the loss with respect to each of the variables. TensorFlow has a variety of built-in optimization algorithms. For this example, we will use steepest gradient descent, with a step length of 0.5, to descend the cross entropy."

In [6]:
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)


"What TensorFlow actually did in that single line was to add new operations to the computation graph. These operations included ones to compute gradients, compute parameter update steps, and apply update steps to the parameters.

The returned operation train_step, when run, will apply the gradient descent updates to the parameters. Training the model can therefore be accomplished by repeatedly running train_step."

In [7]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

sess = tf.InteractiveSession()

x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

W = tf.Variable(tf.zeros([784,10]))
b = tf.Variable(tf.zeros([10]))

sess.run(tf.global_variables_initializer())

y = tf.matmul(x,W) + b

cross_entropy = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y))

train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

#the training code
for _ in range(1000):
    batch = mnist.train.next_batch(100)
    train_step.run(feed_dict={x: batch[0], y_: batch[1]})


Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


"We load 100 training examples in each training iteration. We then run the train_step operation, using feed_dict to replace the placeholder tensors x and y_ with the training examples. Note that you can replace any tensor in your computation graph using feed_dict -- it's not restricted to just placeholders."

### Evaluate the Model

"How well did our model do?

First we'll figure out where we predicted the correct label. tf.argmax is an extremely useful function which gives you the index of the highest entry in a tensor along some axis. For example, tf.argmax(y,1) is the label our model thinks is most likely for each input, while tf.argmax(y_,1) is the true label. We can use tf.equal to check if our prediction matches the truth."

In [8]:
correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))

"That gives us a list of booleans. To determine what fraction are correct, we cast to floating point numbers and then take the mean. For example, [True, False, True, True] would become [1,0,1,1] which would become 0.75."

In [10]:
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

"Finally, we can evaluate our accuracy on the test data. This should be about 92% correct."

In [11]:
print(accuracy.eval(feed_dict={x: mnist.test.images, y_: mnist.test.labels}))

0.9204


In [5]:
#all code together

import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

sess = tf.InteractiveSession()

x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

W = tf.Variable(tf.zeros([784,10]))
b = tf.Variable(tf.zeros([10]))

tf.global_variables_initializer().run()

y = tf.matmul(x,W) + b

cross_entropy = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits(labels=y_, logits=y))

train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

#the training code
for _ in range(3000):
    batch = mnist.train.next_batch(100)
    train_step.run(feed_dict={x: batch[0], y_: batch[1]})
    

correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print(accuracy.eval(feed_dict={x: mnist.test.images, y_: mnist.test.labels}))

sess.close()

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
0.9217


## Build a Multilayer Convolutional Network

### Weight Initialization

"To create this model, we're going to need to create a lot of weights and biases. One should generally initialize weights with a small amount of noise for symmetry breaking, and to prevent 0 gradients. Since we're using ReLU neurons, it is also good practice to initialize them with a slightly positive initial bias to avoid "dead neurons". Instead of doing this repeatedly while we build the model, let's create two handy functions to do it for us."

In [1]:
def weight_variable(shape):
  initial = tf.truncated_normal(shape, stddev=0.1)
  return tf.Variable(initial)

def bias_variable(shape):
  initial = tf.constant(0.1, shape=shape)
  return tf.Variable(initial)


### Convolution and Pooling

"TensorFlow also gives us a lot of flexibility in convolution and pooling operations. How do we handle the boundaries? What is our stride size? In this example, we're always going to choose the vanilla version. Our convolutions uses a stride of one and are zero padded so that the output is the same size as the input. Our pooling is plain old max pooling over 2x2 blocks. To keep our code cleaner, let's also abstract those operations into functions."

what is convolution?

from: http://timdettmers.com/2015/03/26/convolution-deep-learning/

formula and analogy with m.l.

<img src="imgs/convolution-theorem1.png">

<img src="imgs/cross-correlation2.png">

Difference between cross-correlated and convoluted??

from: https://dsp.stackexchange.com/q/27451

<img src="imgs/nGZQ1.png">

from: https://dsp.stackexchange.com/a/27453

"In signal processing, two problems are common:

    What is the output of this filter when its input is x(t)

? The answer is given by x(t)∗h(t), where h(t) is a signal called the "impulse response" of the filter, and ∗

is the convolution operation.

Given a noisy signal y(t)
, is the signal x(t) somehow present in y(t)? In other words, is y(t) of the form x(t)+n(t), where n(t) is noise? The answer can be found by the correlation of y(t) and x(t). If the correlation is large for a given time delay τ

    , then we may be confident in saying that the answer is yes.

Note that when the signals involved are symmetric, convolution and cross-correlation become the same operation; this case is also very common in some areas of DSP."

from: https://dsp.stackexchange.com/a/27452

"The two terms convolution and cross-correlation are implemented in a very similar way in DSP.

Which one you use depends on the application.

If you are performing a linear, time-invariant filtering operation, you convolve the signal with the system's impulse response.

If you are "measuring the similarity" between two signals, then you cross-correlate them.

The two terms come together when you try to produce a matched filter.

Here, you are trying to decide whether a given signal, s[n]
contains a known "pulse" (signal), p[n]. One way to do that is to convolve the given signal, s with the time-reversal of the known pulse, p : you are now using convolution to perform the cross-correlation of the given signal with the known pulse."

More insight, from: https://adeshpande3.github.io/adeshpande3.github.io/A-Beginner's-Guide-To-Understanding-Convolutional-Neural-Networks/ <!--read -->
from: https://www.quora.com/What-is-a-downsampling-layer-in-Convolutional-Neural-Network-CNN/answer/Pallab-Maji?srid=JuUk
(downsampling) (pooling)<!--read --><br>
a must read: http://neuralnetworksanddeeplearning.com/ <!--not read --><br>
recommended course: http://cs231n.stanford.edu/ <!--not taken --><br>
a must read paper: http://www.matthewzeiler.com/wp-content/uploads/2017/07/arxive2013.pdf <!--not read --><br>
a video: https://www.youtube.com/watch?v=AgkfIQ4IGaM <!--not see -->

from: https://adeshpande3.github.io/adeshpande3.github.io/A-Beginner's-Guide-To-Understanding-Convolutional-Neural-Networks-Part-2/
<img src="imgs/output-size.jpeg">

more of convolutional network to think about

<img src="imgs/interesting-nn.jpeg">

more to understand
from: https://adeshpande3.github.io/adeshpande3.github.io/The-9-Deep-Learning-Papers-You-Need-To-Know-About.html

### First Convolutional Layer

"We can now implement our first layer. It will consist of convolution, followed by max pooling. The convolution will compute 32 features for each 5x5 patch. Its weight tensor will have a shape of [5, 5, 1, 32]. The first two dimensions are the patch size, the next is the number of input channels, and the last is the number of output channels. We will also have a bias vector with a component for each output channel."

In [3]:
W_conv1 = weight_variable([5, 5, 1, 32])
b_conv1 = bias_variable([32])


NameError: name 'tf' is not defined

In [5]:
#all code till 'first convolutional layer first paragraph
import tensorflow as tf

def weight_variable(shape):
  initial = tf.truncated_normal(shape, stddev=0.1)
  return tf.Variable(initial)

def bias_variable(shape):
  initial = tf.constant(0.1, shape=shape)
  return tf.Variable(initial)

W_conv1 = weight_variable([5, 5, 1, 32])
b_conv1 = bias_variable([32])

"To apply the layer, we first reshape x to a 4d tensor, with the second and third dimensions corresponding to image width and height, and the final dimension corresponding to the number of color channels."

In [6]:
x_image = tf.reshape(x, [-1, 28, 28, 1])


NameError: name 'x' is not defined

What is x??

from: https://raw.githubusercontent.com/tensorflow/tensorflow/r1.3/tensorflow/examples/tutorials/mnist/mnist_deep.py

<pre>
def deepnn(x):
  """deepnn builds the graph for a deep net for classifying digits.

  Args:
    x: an input tensor with the dimensions (N_examples, 784), where 784 is the
    number of pixels in a standard MNIST image.

  Returns:
    A tuple (y, keep_prob). y is a tensor of shape (N_examples, 10), with values
    equal to the logits of classifying the digit into one of 10 classes (the
    digits 0-9). keep_prob is a scalar placeholder for the probability of
    dropout.
  """
  # Reshape to use within a convolutional neural net.
  # Last dimension is for "features" - there is only one here, since images are
  # grayscale -- it would be 3 for an RGB image, 4 for RGBA, etc.
  with tf.name_scope('reshape'):
    x_image = tf.reshape(x, [-1, 28, 28, 1])
    
</pre>


So x must be defined before

In [9]:
# code adding variable x for input (N_examples, 784)
import tensorflow as tf

from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)


def weight_variable(shape):
  initial = tf.truncated_normal(shape, stddev=0.1)
  return tf.Variable(initial)

def bias_variable(shape):
  initial = tf.constant(0.1, shape=shape)
  return tf.Variable(initial)


x = tf.placeholder(tf.float32, shape=[None, 784])
y_ = tf.placeholder(tf.float32, shape=[None, 10])

W_conv1 = weight_variable([5, 5, 1, 32])
b_conv1 = bias_variable([32])

x_image = tf.reshape(x, [-1, 28, 28, 1])


#works fine

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


Now, why the reshape on the variable 'x' (input data)?

784 stands for 28 * 28 matrix of pixels, 28 height by 28 width

None for any number of images to train

first understanding the '-1' argument in 
tf.reshape(x, [-1, 28, 28, 1])

from: https://www.tensorflow.org/api_docs/python/tf/reshape


In [3]:
import tensorflow as tf

t = [1, 2, 3, 4, 5, 6, 7, 8, 9]
#for pass an array to tensorflow array
#   https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor
t = tf.convert_to_tensor(t)
print(t)
print(t.get_shape)

t1 = tf.reshape(t, [3, 3])
print(t1)
print(t1.get_shape)


Tensor("Const:0", shape=(9,), dtype=int32)
<bound method Tensor.get_shape of <tf.Tensor 'Const:0' shape=(9,) dtype=int32>>
Tensor("Reshape:0", shape=(3, 3), dtype=int32)
<bound method Tensor.get_shape of <tf.Tensor 'Reshape:0' shape=(3, 3) dtype=int32>>


In [10]:
#to get the values it is need it to
#sess.run
import tensorflow as tf

sess = tf.InteractiveSession()

t = [1, 2, 3, 4, 5, 6, 7, 8, 9]
#for pass an array to tensorflow array
#   https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor
t = tf.convert_to_tensor(t)
print(t.get_shape)
print(t.eval())

t1 = tf.reshape(t, [3, 3])
print(t1.get_shape)
print(t1.eval())

t2 = [[[1, 1], [2, 2]], [[3, 3], [4, 4]]]
t2 = tf.convert_to_tensor(t2)
print(t2.get_shape)
print(t2.eval())

sess.close()


<bound method Tensor.get_shape of <tf.Tensor 'Const_7:0' shape=(9,) dtype=int32>>
[1 2 3 4 5 6 7 8 9]
<bound method Tensor.get_shape of <tf.Tensor 'Reshape_10:0' shape=(3, 3) dtype=int32>>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<bound method Tensor.get_shape of <tf.Tensor 'Const_8:0' shape=(2, 2, 2) dtype=int32>>
[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]
